### ISSUE TITLE
Overture Tiles ECR Repository

### ISSUE THREAD

**Issue by charliemcgrady** [OvertureMaps/overture-tiles#19]
### Is your feature request related to a problem? Please describe

The Overture Tiles image is currently hosted in the Protomaps ECR repository: `protomaps/overture-tiles`. Overture should likely manage the repository and process for publishing new versions of the overture tiles image.

### Describe the solution you'd like

- Addition to Overture Tiles CDK which creates an ECR image repository owned by Overture.
- Documentation for the process for publishing new versions of the overture tiles image.

**Comment by bdon** [comment]
I imagine it would be like:

1) provision an ECR repository using CDK, pointing at the image name `overture-tiles/latest`
2) use the AWS web console to authenticate your Docker client with the ECR repository
3) Most code changes can happen with `docker push ...` 

Is there any higher-level automation possible with CDK around this workflow?

**Comment by charliemcgrady** [comment]
Those are the steps I had in mind as well.

Higher level automation is [possible](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_ecr_assets-readme.html), but not via an officially supported construct - https://github.com/aws/aws-cdk/issues/12597. I think manually publishing the image for now is best.

**Comment by bdon** [comment]
Marking this as complete.
