### ISSUE TITLE
Buildings minimal LOD

### ISSUE THREAD

**Issue by bdon** [OvertureMaps/overture-tiles#6]
@jenningsanderson

The source issue may be that the `sources` attribute is only included at zoom 14: https://github.com/bdon/overture-tiles/blob/main/profiles/Buildings.java#L11

So geometries are in the tileset at 13 and below for large buildings, but they do not include the tags you want to categorize by. 

We could special-case the `sources` key to appear at lower zooms, or we could include everything at z13.

**Comment by jenningsanderson** [comment]
Awesome — can we consider including everything at z13? 

Here's what I see: 
z13.99: 
![image](https://github.com/bdon/overture-tiles/assets/1637425/1232dbee-1e6b-4b31-8d56-277f4586b9fc)
z14.01:
![image](https://github.com/bdon/overture-tiles/assets/1637425/84add742-15b1-4442-9ac2-8675f5d4e2a9)

(This is a bit of wishlist — if it's too much data to bake in all building features and attributes at z13, that's fine, too.

**Comment by bdon** [comment]
@jenningsanderson what filter are you applying in your style?

I'm working on instructions to generate the tileset right now - will be a good dogfood test

**Comment by bdon** [comment]
@jenningsanderson could you try these instructions on a subset of data (at minimum just one .parquet file for buildings?)

https://github.com/bdon/overture-tiles?tab=readme-ov-file#other-environments

```
java -cp planetiler.jar profiles/Buildings.java --data=overture
```

**Comment by bdon** [comment]
@skmoore may also be interested in running the tile gen to adjust detail for San Diego

**Comment by jenningsanderson** [comment]
@bdon — here's my style / filters: https://github.com/OvertureMaps/docs/blob/16cca7688062ecb81266b535b664b9c714e1c516/src/components/buildings-map.js#L146

**Comment by jenningsanderson** [comment]
> @jenningsanderson could you try these instructions on a subset of data (at minimum just one .parquet file for buildings?)
> 
> https://github.com/bdon/overture-tiles?tab=readme-ov-file#other-environments
> 
> ```
> java -cp planetiler.jar profiles/Buildings.java --data=overture
> ```

Works perfectly! ( I did have to upgrade to Java 22, but you list those in the instructions, so that's fine!)

**Comment by bdon** [comment]
@jenningsanderson yeah, I don't have a good solution to that beyond the first file usually ends up somewhere around Santiago, Chile. 

Based on your style we could lift the sources property only to a higher level, or even lift just the text string "OpenStreetMap" into a helper attribute like `@source`? do you anticipate visualizing any other properties in the docs?

**Comment by jenningsanderson** [comment]
I think that'd be a great solution — Just lifting out sources[1].dataset to a @sources_1_dataset attribute for buildings to a higher zoom would definitely work for now!

**Comment by bdon** [comment]
@jenningsanderson should this be sources[0].dataset? is the first entry in the struct the "preferred" one?

https://docs.overturemaps.org/schema/attributes/

**Comment by bdon** [comment]
I am thinking of lifting `@sources_0_dataset` on ALL themes instead of just buildings, if that would help visualization for internal use cases; that should have minimal impact on feature size.

**Comment by bdon** [comment]
In some cases like `addresses` the `sources[0].dataset` value is not a small set like `OpenStreetMap`, `Bing` but something more detailed like `OpenAddresses/Bundesamt für Eich- und Vermessungswesen`. This would inflate the tile size significantly for that theme.

**Comment by bdon** [comment]
@jenningsanderson there is a `@sources_0_dataset` helper attribute attached to every building now: 

https://pmtiles.io/?url=https%3A%2F%2Fd32gfzcnkb85e2.cloudfront.net%2F2024-06-13-beta%2Fbuildings.pmtiles#map=10.52/51.3392/4.7124

This updated the 2024-06-13-beta tileset in place.

**Comment by jenningsanderson** [comment]
👍 Awesome.

There is a convention in buildings that the first entry in sources is the source that contains the geometry, which I would consider the `primary` source because that is most important to the building footprint, but `primary` might mean different things across themes. 

For now though, this totally works, thank you!

**Comment by jenningsanderson** [comment]
> 1-based indexing in DuckDB: [duckdb/duckdb#2575](https://github.com/duckdb/duckdb/issues/2575)

Yeah, do we want to make that @sources_1_dataset — or, better yet, we could specifically call out the `geometry` source. 

It would basically be where `property` = ( 'properties/geometry' or `property` = '' ).

**Comment by bdon** [comment]
So the logic should iterate through the `sources` list and find the first matching that condition?

Then should we rename the property to something other than `sources_0_dataset` or `sources_1_dataset`?

if I change the property name in-place we'll have to update the style to read from that, in the intermediate time it may break...

**Comment by jenningsanderson** [comment]
I do think that would be useful, personally, just for the data viz. We could call it `@geometry_source`. Not to take this too far, but it might also be interesting to pull out the source for height as `@height_source`, as well, then we can easily show where USGS Lidar heights are applied to buildings.

The logic for that would be: 

If there is an entry in `sources` where `property='properties/height'`, then use the `dataset` value from that entry. 

Otherwise, if `height` is not null and there is no specific `properties/height` source, then return `dataset` where `property=''`.

**Comment by bdon** [comment]
@jenningsanderson the tileset has been updated: https://pmtiles.io/?url=https%3A%2F%2Foverturemaps-tiles-us-west-2-beta.s3.amazonaws.com%2F2024-07-22%2Fbuildings.pmtiles

<img width="864" alt="Screenshot 2024-07-25 at 21 59 50" src="https://github.com/user-attachments/assets/eb6baeba-0cec-46c1-aff9-18fcfd833c68">

Let me know when your code is updated and I'll remove `source_0_dataset`

**Comment by jenningsanderson** [comment]
Thanks @bdon! I just updated the buildings guide to pull from this new attribute.

**Comment by bdon** [comment]
Tileset has been updated on S3.
